# [ubuntu]
# additional_packages="git vim tmux nodejs"
# image=ubuntu:latest
# init=false
# nvidia=false
# pull=true
# root=false
# replace=true
# start_now=false
# 
# # You can add comments using this #
# [arch] # also inline comments are supported
# additional_packages="git vim tmux nodejs"
# home=/tmp/home
# image=archlinux:latest
# init=false
# start_now=true
# init_hooks="touch /init-normal"
# nvidia=true
# pre_init_hooks="touch /pre-init"
# pull=true
# root=false
# replace=false
# volume="/tmp/test:/run/a /tmp/test:/run/b"

[safesign]
image=ubuntu:20.04
replace=true
start_now=true
#pre_init_hooks="export SHELL=/bin/bash;" # Set login shell
#pre_init_hooks="export CONTAINER_HOME=$HOME/.distrobox/safesign;"
# pre_init_hooks="DEBIAN_FRONTEND=noninteractive dpkg --configure -a"
pre_init_hooks="rm -rf /tmp/safesign" # Clean up any previous temporary files
; pre_init_hooks="rm -rf $HOME/.distrobox/safesign" # Clean up any previous Firefox user profile directory
additional_packages="libpcsclite1 libgdbm-compat4 libwxbase3.0-0v5 libwxgtk3.0-gtk3-0v5 pcscd" # Dependencies for SafeSign Identity Client package
additional_packages="libnss3-tools firefox" # Install Firefox to access the SafeSign Security module
init_hooks="mkdir -p /tmp/safesign" # Create a temporary directory for downloading assets
init_hooks="curl -L -o /tmp/safesign/SafeSign.deb https://github.com/henrikcorrea/safesign-distrobox/raw/main/SafeSign_IC_Standard_Linux_3.7.0.0_AET.000_ub2004_x86_64.deb" # Download the SafeSign Identity Client package directly to the container
init_hooks="dpkg -i /tmp/safesign/SafeSign.deb" # Install the SafeSign Identity Client package
#init_hooks='mkdir -p $HOME/.distrobox/safesign/firefox' # Create firefox user profile directory
#init_hooks='chown -R --reference="$HOME" "$HOME/.distrobox"' # Set ownership of the firefox user profile directory to match the host user
#init_hooks='firefox --no-remote --profile $HOME/.distrobox/safesign/firefox --headless & sleep 5; kill %1'
#init_hooks='modutil -dbdir sql:$HOME/.distrobox/safesign/firefox -add "SafeSign Module" -libfile /usr/lib/libaetpkss.so.3.8.4.2 -force' # Install the SafeSign Security module into the Firefox user profile
#init_hooks='distrobox-export --app firefox --extra-flags "--no-remote --profile $HOME/.distrobox/safesign/firefox"'
volume="/run/pcscd/:/run/pcscd/" # Mount the host's pcscd socket to allow the container to communicate with smart card readers connected to the host
